### PR TITLE
Revert "Add package blocks to pcl conversion. (#221)"

### LINKED ISSUE #224: Workflow failure: Run Acceptance Tests from Cron
## Workflow Failure

[Run Acceptance Tests from Cron](https://github.com/pulumi/pulumi-converter-terraform/blob/main/.github/workflows/cron.yml) has failed. See the list of failures below:

- [2024-11-18T08:01:27.000Z](https://github.com/pulumi/pulumi-converter-terraform/actions/runs/11888120868)

- [2024-11-19T08:09:06.000Z](https://github.com/pulumi/pulumi-converter-terraform/actions/runs/11908616513)

- [2024-11-20T08:09:11.000Z](https://github.com/pulumi/pulumi-converter-terraform/actions/runs/11929090700)

- [2024-11-21T08:09:20.000Z](https://github.com/pulumi/pulumi-converter-terraform/actions/runs/11948970044)

- [2024-11-22T08:09:26.000Z](https://github.com/pulumi/pulumi-converter-terraform/actions/runs/11968700105)

- [2024-11-23T08:09:45.000Z](https://github.com/pulumi/pulumi-converter-terraform/actions/runs/11985467530)

- [2024-11-24T08:09:43.000Z](https://github.com/pulumi/pulumi-converter-terraform/actions/runs/11994378101)

- [2024-11-25T08:09:13.000Z](https://github.com/pulumi/pulumi-converter-terraform/actions/runs/12005644324)

- [2024-11-26T08:02:29.000Z](https://github.com/pulumi/pulumi-converter-terraform/actions/runs/12026223895)

### PR DESCRIPTION
**Pull request by Frassle**
This reverts commit ccb6e15d26933d24e89075b1b6cb85749f522f2a.

Fixes #224

### CODE REVIEW

**Comment by Frassle** [comment]
Seeing if this fixes the example tests

**Review by julienp — APPROVED** [review]
Is there an original issue that implemented this that we can reference & re-open so we don't lose track of this?

**Review by justinvp — APPROVED** [review]
LGTM

How are we going to enable this without breaking bridged providers?

**Comment by Frassle** [comment]
> How are we going to enable this without breaking bridged providers?

Not sure. I need to look into that package block PR more thoroughly next week I think.

**Comment by brandonpollack23** [comment]
I think I figured this out, it has to do with the package name mismatch problem, i'll upload a CL to pulumi/pulumi to show this:

pulumi/pulumi#17889

**Pull request merged**
